"""Generate synthetic anime poster fixture images.

Renders 6 minimal "poster" PNGs into ``ai-worker/fixtures/posters/`` —
each one combines a title, subtitle, a colored block, and a couple of
silhouette shapes so a vision provider has something visual to caption
beyond raw OCR. The output is intentionally placeholder-grade because
the multimodal anime eval is a demo signal, not a benchmark pillar.

Posters are rendered programmatically with Pillow, so every image is
original / self-authored with no license entanglement; we drop a
``LICENSE.md`` note in the directory to make that explicit.

Usage (from ``ai-worker/``)::

    python -m scripts.make_anime_poster_fixtures
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import List, Tuple

log = logging.getLogger("scripts.make_anime_poster_fixtures")


_LICENSE_BODY = """\
# Anime poster fixtures — license note

These PNG files are synthetic, programmatically rendered placeholders
generated by `scripts.make_anime_poster_fixtures`. They contain no
copyrighted artwork, characters, or trademarks — only basic shapes,
gradients, and Korean text matching the `anime_kr.jsonl` doc IDs.

License: CC0 / public domain. They exist purely to give the multimodal
eval harness a non-empty image+text payload to exercise.
"""


_POSTERS: List[dict] = [
    {
        "filename": "anime-kr-001.png",
        "title": "별빛 도서관의 사서",
        "subtitle": "야간 전용 도서관의 견습 사서",
        "primary_rgb": (40, 30, 90),       # deep night blue
        "accent_rgb":  (240, 220, 130),    # warm starlight
        "motif": "stars",
    },
    {
        "filename": "anime-kr-002.png",
        "title": "남쪽 항구의 등불 수리공",
        "subtitle": "폭풍 계절의 등대 정비사",
        "primary_rgb": (20, 60, 90),       # harbor blue
        "accent_rgb":  (255, 200, 100),    # lighthouse beam
        "motif": "lighthouse",
    },
    {
        "filename": "anime-kr-003.png",
        "title": "구름 위의 우편 배달부",
        "subtitle": "비행선 사이를 오가는 견습",
        "primary_rgb": (200, 220, 240),    # cloud sky
        "accent_rgb":  (90, 110, 160),
        "motif": "balloons",
    },
    {
        "filename": "anime-kr-005.png",
        "title": "겨울 산장의 시계공",
        "subtitle": "고립된 산장의 미스터리",
        "primary_rgb": (180, 200, 220),    # snowy gray
        "accent_rgb":  (60, 60, 90),
        "motif": "clock",
    },
    {
        "filename": "anime-kr-006.png",
        "title": "사라진 노선의 차장",
        "subtitle": "마지막 운행이 끝난 폐역",
        "primary_rgb": (60, 50, 50),       # dusk brown
        "accent_rgb":  (200, 160, 80),     # platform light
        "motif": "rails",
    },
    {
        "filename": "anime-kr-009.png",
        "title": "여름 라디오의 신호수",
        "subtitle": "외딴 섬의 임시 신호수",
        "primary_rgb": (90, 130, 120),     # summer green-blue
        "accent_rgb":  (250, 230, 150),    # sunset
        "motif": "tower",
    },
]


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        log.error("Pillow is required (`pip install Pillow`). Aborting.")
        return 2

    out_dir = Path(__file__).resolve().parent.parent / "fixtures" / "posters"
    out_dir.mkdir(parents=True, exist_ok=True)
    log.info("Writing %d posters to %s", len(_POSTERS), out_dir)

    title_font = _load_korean_font(ImageFont, 36)
    subtitle_font = _load_korean_font(ImageFont, 22)
    fallback_font = _load_font(ImageFont, 20)

    if title_font is None or subtitle_font is None:
        log.warning(
            "No Korean font available. Posters will use fallback font and "
            "Korean glyphs will appear as boxes — the OCR target stays valid "
            "but vision quality drops. Install malgun.ttf / NanumGothic to fix."
        )

    for poster in _POSTERS:
        path = out_dir / poster["filename"]
        _render_poster(
            Image, ImageDraw, path,
            title=poster["title"],
            subtitle=poster["subtitle"],
            primary=poster["primary_rgb"],
            accent=poster["accent_rgb"],
            motif=poster["motif"],
            title_font=title_font or fallback_font,
            subtitle_font=subtitle_font or fallback_font,
        )
        log.info("wrote %s", path.name)

    license_path = out_dir / "LICENSE.md"
    license_path.write_text(_LICENSE_BODY, encoding="utf-8")
    log.info("wrote %s", license_path.name)
    return 0


def _render_poster(
    Image, ImageDraw, path: Path, *,
    title: str, subtitle: str,
    primary: Tuple[int, int, int],
    accent:  Tuple[int, int, int],
    motif:   str,
    title_font, subtitle_font,
) -> None:
    width, height = 480, 720
    img = Image.new("RGB", (width, height), color=primary)
    draw = ImageDraw.Draw(img)

    # Vertical gradient band along the bottom for visual interest.
    for i in range(height // 3):
        ratio = i / max(1, height // 3)
        r = int(primary[0] * (1 - ratio) + accent[0] * ratio * 0.4)
        g = int(primary[1] * (1 - ratio) + accent[1] * ratio * 0.4)
        b = int(primary[2] * (1 - ratio) + accent[2] * ratio * 0.4)
        draw.line([(0, height - i), (width, height - i)], fill=(r, g, b))

    if motif == "stars":
        for x, y, r in [(80, 120, 10), (180, 180, 6), (340, 90, 8),
                        (400, 170, 5), (60, 250, 7), (300, 280, 9)]:
            draw.ellipse([x - r, y - r, x + r, y + r], fill=accent)
    elif motif == "lighthouse":
        draw.rectangle([200, 120, 280, 480], fill=accent)
        draw.polygon([(170, 120), (310, 120), (240, 70)], fill=accent)
        draw.ellipse([200, 280, 280, 360], fill=primary)
    elif motif == "balloons":
        for x, y, r in [(100, 200, 60), (260, 140, 70), (380, 240, 50)]:
            draw.ellipse([x - r, y - r, x + r, y + r], fill=accent)
    elif motif == "clock":
        cx, cy, r = 240, 280, 130
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=accent)
        draw.line([(cx, cy), (cx, cy - r + 20)], fill=primary, width=8)
        draw.line([(cx, cy), (cx + r - 30, cy)], fill=primary, width=6)
    elif motif == "rails":
        draw.rectangle([100, 360, 380, 380], fill=accent)
        draw.rectangle([100, 420, 380, 440], fill=accent)
        for tie_x in range(110, 380, 30):
            draw.rectangle([tie_x, 380, tie_x + 12, 420], fill=primary)
    elif motif == "tower":
        draw.polygon([(220, 100), (260, 100), (290, 480), (190, 480)], fill=accent)
        draw.line([(240, 80), (240, 50)], fill=accent, width=6)

    # Title + subtitle band.
    band_top = height - 200
    draw.rectangle([0, band_top, width, height], fill=(0, 0, 0))
    draw.text((30, band_top + 30), title, fill=(245, 245, 245), font=title_font)
    draw.text((30, band_top + 100), subtitle, fill=(190, 190, 190), font=subtitle_font)

    img.save(path, format="PNG")


def _load_korean_font(ImageFont, size: int):
    candidates = [
        r"C:\Windows\Fonts\malgun.ttf",
        r"C:\Windows\Fonts\NanumGothic.ttf",
        "/System/Library/Fonts/AppleSDGothicNeo.ttc",
        "/usr/share/fonts/truetype/nanum/NanumGothic.ttf",
    ]
    for c in candidates:
        try:
            return ImageFont.truetype(c, size=size)
        except Exception:
            continue
    return None


def _load_font(ImageFont, size: int):
    candidates = [
        r"C:\Windows\Fonts\arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for c in candidates:
        try:
            return ImageFont.truetype(c, size=size)
        except Exception:
            continue
    return ImageFont.load_default()


if __name__ == "__main__":
    sys.exit(main())
