"""Image FAISS index — thin wrapper around FaissIndex.

Stores CLIP image embeddings in a subdirectory (``{rag_index_dir}/image/``)
separate from the text index. Reuses :class:`FaissIndex` for all vector
operations and adds an image-specific metadata dataclass.

The build.json sidecar at ``{rag_index_dir}/image/build.json`` records the
CLIP model and dimension used, mirroring the text index convention.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np

from app.capabilities.rag.faiss_index import FaissIndex, IndexBuildInfo


@dataclass(frozen=True)
class ImageMeta:
    """Metadata for a single indexed image."""

    image_id: str
    doc_id: str
    page_number: Optional[int] = None
    source_uri: Optional[str] = None
    sha256: Optional[str] = None
    caption: Optional[str] = None  # from ingest manifest, NOT generated by CLIP
    section_hint: Optional[str] = None


class ImageFaissIndex:
    """FAISS vector index for CLIP image embeddings."""

    def __init__(self, index_dir: Path) -> None:
        self._faiss = FaissIndex(Path(index_dir) / "image")

    def build(
        self,
        vectors: np.ndarray,
        *,
        index_version: str,
        embedding_model: str,
    ) -> IndexBuildInfo:
        return self._faiss.build(
            vectors,
            index_version=index_version,
            embedding_model=embedding_model,
        )

    def load(self) -> IndexBuildInfo:
        return self._faiss.load()

    @property
    def info(self) -> IndexBuildInfo:
        return self._faiss.info

    def search(
        self, query_vectors: np.ndarray, top_k: int
    ) -> List[List[Tuple[int, float]]]:
        return self._faiss.search(query_vectors, top_k)
